nyx-space/anise

- anise-cli/src/main.rs
- anise-gui/src/ui.rs
- anise-py/README.md
- anise/src/almanac/metaload/metaalmanac.rs
- anise/src/almanac/mod.rs
- anise/src/astro/orbit.rs
- anise/src/math/interpolation/mod.rs
- anise/src/structure/lookuptable.rs
This pull request fixes some typos.
No change
No change
Typos are fixed.
No change
No functionality is added, removed or changed, so no additional tests are created
> Fix some typos

- .github/workflows/rust.yml
Just a chore that should have been done months ago.
No change
No change
No change
No change
> Add Rust release job

- anise-gui/Cargo.toml
Update egui to 0.27, along with all of the related dependencies.
No change
No change
No change
No change
> Fixed egui dependencies

- .github/workflows/python.yml
- anise/src/almanac/metaload/metafile.rs
Closes #242 .
No change
+ Support absolute paths in Windows style for MetaFile (part of MetaAlmanac).
No change
No change
> Support windows absolute paths in meta almanac

- .github/workflows/rust.yml
- Cargo.toml
- anise-gui/src/ui.rs
- anise/Cargo.toml
- anise/src/almanac/embed.rs
- anise/src/almanac/mod.rs
Switch to the released alpha version of hifitime v4.
Closes #260 
No change
No change
No change
No change
No change.
> Now using hifitime 4.0.0-alpha

- anise-gui/Cargo.toml
- anise-gui/src/main.rs
- anise-gui/src/ui.rs
Switch to catppuccin theme + egui 0.28
No change
No change
No change
No change
No change
> Switch to catppuccin theme + egui 0.28

- anise/Cargo.toml
> Build --doc without embed_ephem

- anise/Cargo.toml
- anise/README.md
- anise/src/math/cartesian.rs
- anise/src/orientations/rotate_to_parent.rs
- anise/src/structure/dataset/mod.rs
- anise/src/structure/spacecraft/drag.rs
- anise/src/structure/spacecraft/inertia.rs
- anise/src/structure/spacecraft/mass.rs
- anise/src/structure/spacecraft/mod.rs
- anise/src/structure/spacecraft/srp.rs
More fixes that slipped through the radar as I work on https://github.com/nyx-space/nyx/issues/390.
This updates some dev dependencies and again breaks SpacecraftData.
No change
No change
No change
No change
_No change_
> Additional fixes for version 0.5.2

- .github/workflows/python.yml
- Cargo.toml
- anise-gui/Cargo.toml
Close #383 
No change
No change
No change
No change
N/A
> Try to release 0.5.3 on pypi

- anise-gui/README.md
> Fix build instructions for anise-gui

- Cargo.toml
- anise-py/tests/test_almanac.py
- anise/src/almanac/metaload/metafile.rs
- anise/src/almanac/mod.rs
- anise/src/math/interpolation/hermite.rs
- anise/src/naif/daf/file_record.rs
- anise/src/naif/kpl/parser.rs
- anise/src/structure/dataset/error.rs
- data/.gitignore
- data/de421.bsp
- data/de430.bsp
- data/de440.bsp
- data/de440_type3.bsp
- data/de440s.bsp
- data/gm_de440.tpc
_Continuation from #406_
No change
No change
No change
Fixes #339 (when merged)
@translunar added a test case for this bug in Python, thanks Juno!
> Unit test showing convert_tpc not working with gm_de440.tpc

- .github/workflows/python.yml
- .github/workflows/rust.yml
- anise/Cargo.toml
- anise/build.rs
- anise/src/almanac/metaload/metafile.rs
- anise/src/almanac/metaload/mod.rs
- anise/tests/ephemerides/translation.rs
- data/gmat-lagrange.bsp
Switch from the heavy reqwest to the lightweight ureq crate for metaload.
No change
No change
No change
No change
No change.
> Switch from reqwest to ureq

- anise/src/naif/kpl/parser.rs
- anise/src/structure/lookuptable.rs
Closes https://github.com/nyx-space/anise/issues/426
When running the fuzz test for `convert_fk_items` multiple failures were encountered due to unexpected data values or mismatches in array sizes. This pull request aims to fix everything preventing the fuzz test from successfully running via additional error reporting.
No change
No change
No change
Raise additional errors to prevent the program from crashing.
Run related fuzz test for 15 minutes, even though original failure was encountered within 10 seconds.
`cargo fuzz run convert_fk_items -- -max_total_time=900`
> Error Handling for FK Item Conversion

- Cargo.toml
- anise/Cargo.toml
Version bump, nothing more.
No change
No change
No change
No change
> Update anise to 0.6.0

- anise/src/almanac/transform.rs
My applications require these functions very frequently, so I thought it would be cool that ANISE integrate them and to facilitate the development of applications
It is possible that this is the incorrect location to "introduce" those.
> Introduce Unit Vector functions

- Cargo.toml
- anise-py/anise.pyi
- anise-py/src/lib.rs
- anise/src/almanac/eclipse.rs
- anise/src/almanac/python.rs
- anise/src/astro/orbit_geodetic.rs
- anise/tests/astro/eclipsing.rs
- anise/tests/astro/mod.rs
**Add beta angle computation**
No change
- Add beta angle computation as computed in GMAT
- Add `altitude_km` to compute the instantaneous altitude
No change
No change
- Ensure that the beta angle does not vary throughout an orbit
> Add beta angle computation

- anise-py/tests/test_almanac.py
- anise-py/tutorials/Tutorial 05 - Using frame kernels and text planetary kernels.ipynb
- anise/src/naif/kpl/parser.rs
- anise/tests/ephemerides/transform.rs
- anise/tests/test_analysis/lro-occultation.py
- anise/tests/test_analysis/spk_validation_plots.py
**Summarize the proposed changes**
No change
No change
some typos fixed ; one python function simplified ; other minor details in python code
No change
> a few typos and minor details

- anise-gui/src/ui.rs
- anise-py/anise/__init__.py
- anise-py/anise/astro/__init__.py
- anise-py/pyproject.toml
- anise-py/src/bin.rs
- anise-py/src/lib.rs
- anise/src/almanac/metaload/metafile.rs
Uses the `MetaFile` structure to automatically download the ANISE GUI executable from public-data.nyxspace.com on either Linux or Windows. It will check that the CRC32 of the currently available file is the expected one, and if not, it will download it.
Fixes #241 
No change
No change
No change
No change
Locally tested on Linux; to be tested on Windows.
> Add anise-gui executable to Python package

- Cargo.toml
- anise-py/anise/__init__.pyi
- anise-py/anise/time.pyi
Update to hifitime 4.1.2. Update the pyi files too. ANISE now version 0.6.5.
No change
No change
No change
No change
> Deps/hifitime 4.1.2

- anise/fuzz/README.md
Closes https://github.com/nyx-space/anise/issues/470
The fuzz testing documentation is currently lacking and unclear. As part of integrating this into the https://github.com/google/oss-fuzz project, I am proposing some updates to the current documentation.
No change
No change
No change
No change
This is an update to the fuzz testing documentation, specifically. All other documentation will remain untouched.
> Updates to various fuzz files to support oss-fuzz integration

- .github/workflows/python.yml
- Cargo.toml
- anise-py/pyproject.toml
- anise/Cargo.toml
The pyproject.toml file restricted the upper limit of the Python version, so trying to upload the packages for that version caused an error. This removes the upper limit, and version bumps to 0.6.8.
No change
No change
No change
No change
> Version bump 0.6.8 to fix Python release

- anise/src/ephemerides/translations.rs
- anise/tests/ephemerides/translation.rs
- anise/tests/ephemerides/validation/type02_chebyshev_jpl_de.rs
Partially fixes https://github.com/nyx-space/anise/issues/157
Light time only test cases now have zero error
> Light time corrected velocity from spkltc.c
